export const LOAD_FAILED_LIST = 'LOAD_FAILED_LIST';
export const LOAD_NEWS_LIST = 'LOAD_NEWS_LIST';
export const LOAD_STARTED_LIST = 'LOAD_STARTED_LIST';
export const LOAD_SUCCEEDED_LIST = 'LOAD_SUCCEEDED_LIST';
